### ISSUE TITLE
Can I use this in our work project?

### ISSUE THREAD

**Issue by antontuz** [neon-sunset/RangeExtensions#34]
I absolutely love this syntax
`var enumerable = (..100).Select(num => num % 2);` looks amazing 
can I use your extensions in production?

**Comment by neon-sunset** [comment]
Sure, you can. It is tested and will work as intended.

The only single caveat I was thinking about recently is `RangeExtensions` makes tradeoff in its enumerators design - it expects you *not* to call `MoveNext()` after it returned false (which all standard library non-multi-threaded consumers of IEnumerable respect). This is an implementation requirement to keep `RangeEnumerable.Enumerator` (and its projections) structs small while retaining support of reverse ranges (like `100..0`).

Otherwise, you can see that relevant features all covered by tests.
